/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SpacesRouteImport } from './routes/spaces'
import { Route as ChatIndexRouteImport } from './routes/chat.index'
import { Route as ChatIdRouteImport } from './routes/chat.$id'
import { Route as ProfileIdRouteImport } from './routes/profile.$id'
import { Route as ProfileMeRouteImport } from './routes/profile.me'
import { Route as SpacesIndexRouteImport } from './routes/spaces.index'
import { Route as SpacesIdRouteImport } from './routes/spaces.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SpacesRoute = SpacesRouteImport.update({
  id: '/spaces',
  path: '/spaces',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const ChatIdRoute = ChatIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ChatRoute,
} as any)
const ProfileIdRoute = ProfileIdRouteImport.update({
  id: '/profile/$id',
  path: '/profile/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileMeRoute = ProfileMeRouteImport.update({
  id: '/profile/me',
  path: '/profile/me',
  getParentRoute: () => rootRouteImport,
} as any)
const SpacesIndexRoute = SpacesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SpacesRoute,
} as any)
const SpacesIdRoute = SpacesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SpacesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRouteWithChildren
  '/design-system': typeof DesignSystemRoute
  '/feed': typeof FeedRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/spaces': typeof SpacesRouteWithChildren
  '/chat/$id': typeof ChatIdRoute
  '/profile/$id': typeof ProfileIdRoute
  '/profile/me': typeof ProfileMeRoute
  '/spaces/$id': typeof SpacesIdRoute
  '/chat/': typeof ChatIndexRoute
  '/spaces/': typeof SpacesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/design-system': typeof DesignSystemRoute
  '/feed': typeof FeedRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/chat/$id': typeof ChatIdRoute
  '/profile/$id': typeof ProfileIdRoute
  '/profile/me': typeof ProfileMeRoute
  '/spaces/$id': typeof SpacesIdRoute
  '/chat': typeof ChatIndexRoute
  '/spaces': typeof SpacesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRouteWithChildren
  '/design-system': typeof DesignSystemRoute
  '/feed': typeof FeedRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/spaces': typeof SpacesRouteWithChildren
  '/chat/$id': typeof ChatIdRoute
  '/profile/$id': typeof ProfileIdRoute
  '/profile/me': typeof ProfileMeRoute
  '/spaces/$id': typeof SpacesIdRoute
  '/chat/': typeof ChatIndexRoute
  '/spaces/': typeof SpacesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/design-system'
    | '/feed'
    | '/onboarding'
    | '/settings'
    | '/spaces'
    | '/chat/$id'
    | '/profile/$id'
    | '/profile/me'
    | '/spaces/$id'
    | '/chat/'
    | '/spaces/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/design-system'
    | '/feed'
    | '/onboarding'
    | '/settings'
    | '/chat/$id'
    | '/profile/$id'
    | '/profile/me'
    | '/spaces/$id'
    | '/chat'
    | '/spaces'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/design-system'
    | '/feed'
    | '/onboarding'
    | '/settings'
    | '/spaces'
    | '/chat/$id'
    | '/profile/$id'
    | '/profile/me'
    | '/spaces/$id'
    | '/chat/'
    | '/spaces/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRouteWithChildren
  DesignSystemRoute: typeof DesignSystemRoute
  FeedRoute: typeof FeedRoute
  OnboardingRoute: typeof OnboardingRoute
  SettingsRoute: typeof SettingsRoute
  SpacesRoute: typeof SpacesRouteWithChildren
  ProfileIdRoute: typeof ProfileIdRoute
  ProfileMeRoute: typeof ProfileMeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spaces': {
      id: '/spaces'
      path: '/spaces'
      fullPath: '/spaces'
      preLoaderRoute: typeof SpacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/chat/$id': {
      id: '/chat/$id'
      path: '/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof ChatIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/profile/$id': {
      id: '/profile/$id'
      path: '/profile/$id'
      fullPath: '/profile/$id'
      preLoaderRoute: typeof ProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/me': {
      id: '/profile/me'
      path: '/profile/me'
      fullPath: '/profile/me'
      preLoaderRoute: typeof ProfileMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spaces/': {
      id: '/spaces/'
      path: '/'
      fullPath: '/spaces/'
      preLoaderRoute: typeof SpacesIndexRouteImport
      parentRoute: typeof SpacesRoute
    }
    '/spaces/$id': {
      id: '/spaces/$id'
      path: '/$id'
      fullPath: '/spaces/$id'
      preLoaderRoute: typeof SpacesIdRouteImport
      parentRoute: typeof SpacesRoute
    }
  }
}

interface ChatRouteChildren {
  ChatIdRoute: typeof ChatIdRoute
  ChatIndexRoute: typeof ChatIndexRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatIdRoute: ChatIdRoute,
  ChatIndexRoute: ChatIndexRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

interface SpacesRouteChildren {
  SpacesIdRoute: typeof SpacesIdRoute
  SpacesIndexRoute: typeof SpacesIndexRoute
}

const SpacesRouteChildren: SpacesRouteChildren = {
  SpacesIdRoute: SpacesIdRoute,
  SpacesIndexRoute: SpacesIndexRoute,
}

const SpacesRouteWithChildren =
  SpacesRoute._addFileChildren(SpacesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRouteWithChildren,
  DesignSystemRoute: DesignSystemRoute,
  FeedRoute: FeedRoute,
  OnboardingRoute: OnboardingRoute,
  SettingsRoute: SettingsRoute,
  SpacesRoute: SpacesRouteWithChildren,
  ProfileIdRoute: ProfileIdRoute,
  ProfileMeRoute: ProfileMeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
